# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 889026711e65ab6f182d34b99144a0a14da90a5f1005e64ab976f61253c9774cf8e824634882b1e07cfdd9201274ae746ad71031c5773c7febf3d9e7c945a722

test:
  secret_key_base: 81a074a86ad405110f66ab1ec50878f37e2c53cb5f719625812494df8633d93f19de46e96abd34275f9135249155295d64d601475ad35f838b3c41a7c0c088e1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
